"""File 04 — 50 Powerful Hooks.

Each category: (title, why-it-works, [(template, example, best for)]).
Examples are written for different niches so readers can see the pattern
travel. Examples must never contain placeholders.
"""

GLOSSARY = {
    "TOPIC": "The subject of your post — “meal prep”, “pricing”, “Instagram Stories”.",
    "ACTIVITY": "Something your audience does — “running”, “freelancing”, “learning Spanish”.",
    "NICHE": "Your field — “wedding photography”, “personal finance for students”.",
    "RESULT": "An outcome your audience wants — “sleep better”, “land your first client”.",
    "PROBLEM": "A specific struggle — “losing motivation after two weeks”.",
    "GOAL": "What your audience is trying to achieve.",
    "NUMBER": "A specific number. Odd numbers and small numbers tend to read naturally.",
    "TIME PERIOD": "A length of time — “30 days”, “six months”, “a year”.",
    "SITUATION": "Where your viewer is right now — “if you’re about to quit your job”.",
    "ACTION": "Something your viewer is about to do.",
    "THING": "An object, piece of work or result you can show.",
    "COMMON ADVICE": "Advice everyone in your niche repeats.",
    "OPINION": "A view you genuinely hold and can explain.",
    "EMOTION": "How your audience feels — overwhelmed, stuck, behind.",
    "X": "A habit or action you want people to stop.",
    "BEFORE": "The starting situation, described specifically.",
    "AFTER": "The improved situation, described specifically.",
    "STARTING POINT": "Where you (or a customer) began.",
    "OPPORTUNITY": "Something you were offered and turned down.",
    "DECISION": "A choice your audience is about to make.",
    "NEXT STEP": "The next stage in your audience’s journey.",
    "COMMON REQUIREMENT": "Something people believe they need before they start.",
    "POPULAR TREND": "A trend or method everyone seems to be using.",
    "EXPENSIVE THING": "Gear, software or a course people assume they need.",
    "COMMON SACRIFICE": "Something people assume they must give up.",
}

CATEGORIES = [
    (
        "Curiosity",
        "Open a gap between what the viewer knows and what they want to know. Always deliver the answer — curiosity without a payoff feels like clickbait.",
        [
            ("Nobody tells you this about [TOPIC]…",
             "Nobody tells you this about freelancing: the hardest part isn’t finding clients.",
             "Reels, TikTok, carousel covers"),
            ("I tried [ACTIVITY] for [TIME PERIOD]. Here’s what actually happened.",
             "I tried batch-creating my content for 30 days. Here’s what actually happened.",
             "Reels, TikTok, YouTube Shorts"),
            ("The [TOPIC] advice I’d delete from the internet.",
             "The budgeting advice I’d delete from the internet.",
             "Talking-head video, carousel cover"),
            ("There’s a reason your [TOPIC] isn’t working — and it’s not what you think.",
             "There’s a reason your sourdough isn’t rising — and it’s not your starter.",
             "Reels, TikTok"),
            ("[TIME PERIOD] of [ACTIVITY] taught me something no course did.",
             "Six years of wedding photography taught me something no course did.",
             "LinkedIn opener, storytelling Reel"),
            ("Most people skip this step in [ACTIVITY]. It’s the one that matters most.",
             "Most people skip this step when painting a room. It’s the one that matters most.",
             "Tutorial Reels, carousels"),
            ("If you [SITUATION], watch this before you [ACTION].",
             "If you’re about to raise your prices, watch this before you announce it.",
             "Reels, TikTok"),
        ],
    ),
    (
        "Educational",
        "Promise a clear, specific piece of learning. The more concrete the promise, the stronger the hook.",
        [
            ("Here’s how to [RESULT] in [NUMBER] simple steps.",
             "Here’s how to plan a week of family meals in 4 simple steps.",
             "Carousel covers, tutorial Reels"),
            ("[TOPIC], explained in under 60 seconds.",
             "Compound interest, explained in under 60 seconds.",
             "Reels, TikTok, YouTube Shorts"),
            ("The simplest way to [RESULT] — even if you’re a complete beginner.",
             "The simplest way to start journaling — even if you’re a complete beginner.",
             "Carousels, Reels"),
            ("Save this before your next [ACTIVITY].",
             "Save this before your next job interview.",
             "Checklist carousels"),
            ("You don’t need [EXPENSIVE THING] to [RESULT]. You need this.",
             "You don’t need a ring light to film good videos. You need a window.",
             "Reels, carousels"),
            ("Here’s the exact process I use to [RESULT].",
             "Here’s the exact process I use to write a newsletter in one hour.",
             "Carousels, LinkedIn posts"),
            ("If you only learn one thing about [TOPIC], make it this.",
             "If you only learn one thing about houseplants, make it this.",
             "Reels, static posts"),
        ],
    ),
    (
        "Problem",
        "Name the struggle in the words your audience uses. When people feel understood, they keep reading.",
        [
            ("Struggling to [GOAL]? Start here.",
             "Struggling to run 5K without stopping? Start here.",
             "Carousel covers, Reels"),
            ("If [PROBLEM] keeps happening, this is probably why.",
             "If your clients keep paying late, this is probably why.",
             "Reels, LinkedIn posts"),
            ("Tired of [PROBLEM]? Try this instead.",
             "Tired of rewriting the same email ten times? Try this instead.",
             "Reels, TikTok"),
            ("This is for anyone who feels [EMOTION] about [TOPIC].",
             "This is for anyone who feels overwhelmed by their inbox.",
             "Captions, talking-head videos"),
            ("[PROBLEM] isn’t a motivation problem. It’s a system problem.",
             "Skipping workouts isn’t a motivation problem. It’s a system problem.",
             "LinkedIn posts, Reels"),
            ("Still dealing with [PROBLEM] after trying everything? Check this first.",
             "Still dealing with a slow laptop after trying everything? Check this first.",
             "Tutorial Reels, carousels"),
        ],
    ),
    (
        "Mistake",
        "People are wired to avoid losses. Pointing out a mistake — kindly — makes viewers check whether they’re making it.",
        [
            ("Stop doing [X] if you want [RESULT].",
             "Stop posting without a plan if you want consistent engagement.",
             "Reels, carousel covers"),
            ("[NUMBER] mistakes beginners make when [ACTIVITY].",
             "3 mistakes beginners make when learning guitar.",
             "Carousels, Reels"),
            ("I made this [TOPIC] mistake for years. Don’t repeat it.",
             "I made this pricing mistake for years. Don’t repeat it.",
             "Talking-head Reels, LinkedIn"),
            ("The most expensive mistake in [NICHE] is also the most common.",
             "The most expensive mistake in home renovation is also the most common.",
             "Reels, LinkedIn posts"),
            ("If you’re doing [ACTIVITY] like this, you’re making it harder than it needs to be.",
             "If you’re meal prepping like this, you’re making it harder than it needs to be.",
             "Reels, TikTok"),
            ("Avoid this if you’re new to [NICHE].",
             "Avoid this if you’re new to dog training.",
             "Reels, carousel covers"),
        ],
    ),
    (
        "Story",
        "A story hook drops the viewer into a moment. Start as close to the action as you can.",
        [
            ("I wish I knew this when I started [ACTIVITY].",
             "I wish I knew this when I started selling handmade jewelry.",
             "Reels, carousels, LinkedIn"),
            ("The day I almost quit [ACTIVITY]…",
             "The day I almost quit teaching yoga…",
             "Storytime Reels, captions"),
            ("A client asked me something last week that I can’t stop thinking about.",
             "A client asked me something last week that I can’t stop thinking about: “Why do you still do this by hand?”",
             "LinkedIn posts, talking-head videos"),
            ("[TIME PERIOD] ago, I was [STARTING POINT]. Here’s what changed.",
             "Two years ago, I was editing videos on a borrowed laptop. Here’s what changed.",
             "Carousels, Reels"),
            ("This is the most honest thing I’ve shared about [TOPIC].",
             "This is the most honest thing I’ve shared about running a small café.",
             "Captions, LinkedIn posts"),
            ("I said no to [OPPORTUNITY]. Here’s why.",
             "I said no to my biggest client offer this year. Here’s why.",
             "LinkedIn posts, Reels"),
        ],
    ),
    (
        "Contrarian",
        "Challenge a common belief — respectfully and with a reason. Only use opinions you actually hold.",
        [
            ("Unpopular opinion: [COMMON ADVICE] is overrated.",
             "Unpopular opinion: waking up at 5 a.m. is overrated.",
             "Reels, static posts"),
            ("Everyone says [COMMON ADVICE]. I disagree.",
             "Everyone says you should post every day. I disagree.",
             "LinkedIn posts, Reels"),
            ("You don’t need [COMMON REQUIREMENT] to [RESULT].",
             "You don’t need a big following to sell your first digital product.",
             "Reels, carousel covers"),
            ("[POPULAR TREND] isn’t for everyone — and that’s fine.",
             "Minimalist interiors aren’t for everyone — and that’s fine.",
             "Reels, captions"),
            ("The most repeated advice about [TOPIC] is also the least helpful.",
             "The most repeated advice about networking is also the least helpful.",
             "LinkedIn posts, talking-head videos"),
            ("Hot take: [OPINION]. Here’s my reasoning.",
             "Hot take: most small businesses don’t need a website on day one. Here’s my reasoning.",
             "Reels, LinkedIn posts"),
        ],
    ),
    (
        "List",
        "Numbers set expectations. Viewers know how long the content is and what they’ll get.",
        [
            ("[NUMBER] [TOPIC] tips I’d give my beginner self.",
             "5 photography tips I’d give my beginner self.",
             "Carousels, Reels"),
            ("[NUMBER] tools that make [ACTIVITY] easier.",
             "4 tools that make planning content easier.",
             "Carousels"),
            ("[NUMBER] signs you’re ready to [NEXT STEP].",
             "3 signs you’re ready to hire your first employee.",
             "Carousels, LinkedIn posts"),
            ("[NUMBER] things I stopped doing to [RESULT].",
             "6 things I stopped doing to get more focused work done.",
             "Reels, carousels"),
            ("[NUMBER] questions to ask before you [DECISION].",
             "7 questions to ask before you sign a lease.",
             "Carousels, LinkedIn document posts"),
            ("My [NUMBER]-step checklist for [ACTIVITY].",
             "My 5-step checklist for launching a workshop.",
             "Checklist carousels"),
        ],
    ),
    (
        "Before / After",
        "Contrast creates instant interest. Show a real change and be honest about what it took.",
        [
            ("Before: [BEFORE]. After: [AFTER]. Here’s what changed.",
             "Before: three hours writing captions every week. After: forty minutes. Here’s what changed.",
             "Carousels, Reels"),
            ("What my [THING] looked like on day 1 vs. day [NUMBER].",
             "What my handwriting looked like on day 1 vs. day 100.",
             "Reels, carousels"),
            ("Same [THING], two approaches. Which one works better?",
             "Same product photo, two lighting setups. Which one works better?",
             "Carousels, Reels"),
            ("This is what [RESULT] actually looks like behind the scenes.",
             "This is what a “finished” kitchen renovation actually looks like behind the scenes.",
             "Reels, Story sequences"),
            ("How I went from [STARTING POINT] to [RESULT] — without [COMMON SACRIFICE].",
             "How I went from zero savings to an emergency fund — without giving up weekends out.",
             "Carousels, LinkedIn posts"),
            ("Watch this [THING] go from [BEFORE] to [AFTER].",
             "Watch this tired armchair go from faded to fresh.",
             "Reels, TikTok"),
        ],
    ),
]
