"""File 03 — 100 Content Ideas.

Each category: (title, description, [(idea title, explanation, format, CTA)]).
"""

CATEGORIES = [
    (
        "Educational",
        "Teach one useful thing at a time. Educational posts build trust and are the ones people save and come back to.",
        [
            ("The Beginner’s Glossary", "Explain 5–7 terms in your niche that confuse newcomers, using plain language and one everyday example for each.", "Carousel", "Save this for the next time the jargon gets confusing."),
            ("Explain It Like I’m New", "Take one concept your audience finds complicated and explain it with a simple analogy from everyday life.", "Talking-head Reel", "Which topic should I simplify next? Tell me below."),
            ("The 3-Step Starter Plan", "Give a complete beginner the simplest possible path: the first three actions to take, in order, and why.", "Carousel", "Save this and start with step one today."),
            ("Myth vs Reality", "Pick one belief that’s common in your niche and show what actually happens in practice.", "Carousel", "Did you believe this one? Be honest in the comments."),
            ("Tool Walkthrough", "Show how you use one tool for one specific task, start to finish, in under a minute.", "Screen-recording Reel", "Follow for more short walkthroughs like this."),
            ("Common Mistake, Explained", "Break down one mistake: what it looks like, why people make it, and the simple fix.", "Reel", "Send this to someone who’s making this mistake right now."),
            ("The 10-Minute Quick Win", "Share one action that takes under ten minutes and gives a visible result your audience can feel today.", "Reel or static post", "Try it today and tell me how it went."),
            ("Before-You-Start Checklist", "List what someone should prepare, decide or check before they begin [ACTIVITY].", "Checklist carousel", "Save this checklist for when you’re ready to start."),
            ("Option A vs Option B", "Compare two popular approaches honestly: who each one suits, the trade-offs, and what you’d choose in different situations.", "Carousel", "Which one would you pick — A or B?"),
            ("The Reason Behind the Rule", "Explain why a common best practice in your niche exists, so people understand it instead of just following it.", "LinkedIn post or long caption", "What rule did you follow for years without knowing why?"),
            ("Step-by-Step Tutorial", "Teach a complete process in 5–7 clear steps, with one tip or warning at the most commonly missed step.", "Carousel", "Save this so you can follow along later."),
            ("Answer a Real Question", "Take a question someone actually asked you (anonymized) and answer it fully and simply.", "Reel", "Send me your question — I might answer it next."),
            ("Resource Roundup", "Share 5 books, podcasts, tools or courses you have personally used, with one sentence on what each is good for.", "Carousel", "What would you add to this list?"),
            ("Your Framework, Explained", "Introduce a simple method you use repeatedly, give it a name, and explain each step with an example.", "Carousel", "Follow for more frameworks you can use straight away."),
            ("What’s Changed Recently", "Explain one recent change in your field and what it practically means for your audience.", "LinkedIn post", "Have you noticed this change too?"),
            ("Numbers Made Simple", "Walk through a calculation your audience struggles with — a budget, a timeline, a price, a quantity — using a worked example.", "Carousel", "Save this for your next planning session."),
            ("Do This, Not That", "Show four side-by-side pairs: the common approach and the better alternative.", "Carousel", "Share this with a friend who’s just getting started."),
            ("Behind a Result", "Break down how you achieved one specific result: what you did, what didn’t work, and what made the difference.", "Carousel", "Questions about the process? Ask below."),
            ("Red Flags to Watch For", "List warning signs your audience should notice when choosing a product, provider or method in your niche.", "Carousel", "Share this with someone who’s about to make this decision."),
            ("Mini-Lesson, Part 1", "Start a numbered series that teaches one topic in short episodes, ending each with what’s coming next.", "Reel series", "Follow so you don’t miss part 2."),
        ],
    ),
    (
        "Personal / Storytelling",
        "People follow people. Personal stories make your expertise relatable and give your audience a reason to remember you.",
        [
            ("Why I Started", "Share the real reason you got into your field — the moment, the frustration or the person that pushed you.", "Carousel or talking-head Reel", "What made you start? I’d love to know."),
            ("My Biggest Mistake So Far", "Talk honestly about a mistake you made, what it cost you, and what you do differently now.", "Talking-head Reel", "What’s a mistake that taught you the most?"),
            ("A Lesson from a Bad Day", "Describe a frustrating day and the small lesson you took from it.", "Long caption or LinkedIn post", "Tell me about a bad day that turned into a lesson."),
            ("Then vs Now", "Show a side-by-side of your work, setup or skills from when you started compared with today.", "Carousel", "Where are you on your journey right now?"),
            ("The Advice I Ignored", "Share a piece of advice you dismissed, what happened as a result, and when you finally understood it.", "Reel", "What advice did you ignore at first?"),
            ("A Normal Day", "Show what a typical day really looks like — including the unglamorous parts.", "Story sequence or Reel", "Want to see more behind-the-scenes? Let me know."),
            ("The Decision I Almost Didn’t Make", "Tell the story of a choice that felt risky at the time and what it led to.", "LinkedIn post", "Have you made a decision like this?"),
            ("Something I Changed My Mind About", "Explain an opinion you used to hold strongly and what changed your perspective.", "Talking-head Reel", "Have you changed your mind about this too?"),
            ("My Unusual Habit", "Share one habit that’s slightly unusual in your field and why it works for you.", "Static post with long caption", "What’s a habit that works for you but surprises people?"),
            ("My First Customer", "Tell the story of your first client or customer: how they found you, what you got right and what you’d do differently.", "Carousel", "Do you remember your first customer?"),
            ("What I Do When I’m Stuck", "Show your real process for getting unstuck when motivation or ideas run out.", "Reel", "What helps you when you feel stuck?"),
            ("A Small Win This Week", "Celebrate a small, honest win and what made it possible.", "Story or static post", "Share one small win from your week."),
            ("People Who Shaped My Work", "Credit the mentors, creators or colleagues who influenced how you work, and what you learned from each.", "Carousel or caption", "Who has shaped the way you work?"),
            ("The Question I Get Asked Most", "Answer the question people ask you most often — with your personal take, not a textbook answer.", "Talking-head Reel", "Ask me anything else in the comments."),
            ("This Time Last Year", "Look back at where you were a year ago and share what changed — wins, struggles and lessons.", "Photo and caption", "What’s changed for you this year?"),
        ],
    ),
    (
        "Engagement",
        "Posts designed to start conversations. Use them to learn about your audience — the answers often become your next ideas.",
        [
            ("This or That", "Offer two options related to your niche and ask people to pick one.", "Story poll or static post", "Vote in the poll — results tomorrow."),
            ("Fill in the Blank", "Post an unfinished sentence such as “The hardest part of [ACTIVITY] is ______.”", "Static post", "Finish the sentence in the comments."),
            ("Share Your Unpopular Opinion", "Share a mild unpopular opinion of your own, then invite your audience to share theirs.", "Static post or Reel", "Your turn — what’s your unpopular opinion?"),
            ("Rate It from 1 to 10", "Show a tool, setup, method or result and ask people to rate it honestly.", "Reel or static post", "Rate it from 1 to 10 in the comments."),
            ("Caption This", "Post a funny or unusual behind-the-scenes photo and ask your audience to write the caption.", "Static post", "Best caption gets pinned."),
            ("Ask Me Anything", "Open a question box and answer the best questions over the next day or two.", "Story question sticker", "Send me your questions."),
            ("Test Your Knowledge", "Create a short quiz about your niche with the answers revealed on the final slide or in the next Story.", "Story quiz or carousel", "How many did you get right?"),
            ("Pick One Tip", "Share four quick tips and ask people which one they’ll try first.", "Carousel", "Which tip are you trying first — 1, 2, 3 or 4?"),
            ("Help Me Decide", "Ask your audience to help with a real decision: two cover designs, two product names, two topics.", "Story poll or carousel", "Vote and tell me why."),
            ("Share Your Win", "Invite your audience to share something they achieved this week, however small.", "Static post", "Drop your win below — big or small."),
            ("Agree or Disagree?", "Post a clear statement about your niche and ask people where they stand.", "Static post", "Agree or disagree? Tell me why."),
            ("Beginner vs Experienced", "Ask experienced followers what they wish they’d known as beginners, and beginners what they’re struggling with.", "Static post or caption", "Tell me your level and your answer."),
            ("Recommend Something", "Ask your audience for their favorite tool, book or resource related to your niche.", "Static post or Story", "What’s one thing you couldn’t work without?"),
            ("Guess the Answer", "Show something — a price, a time, a before-shot — and ask people to guess before you reveal the answer.", "Reel", "Guess in the comments before the reveal."),
            ("Community Spotlight", "Feature a follower’s great question, comment or result (with their permission).", "Static post or Story", "Want to be featured next? Share your progress."),
        ],
    ),
    (
        "Inspirational",
        "Grounded encouragement — not empty quotes. These ideas work best when they’re based on real experience.",
        [
            ("Progress over Perfection", "Show an early piece of your work next to a recent one, and talk about what changed in between.", "Carousel", "Share your early work — let’s celebrate progress."),
            ("You Don’t Need to Have It All Figured Out", "Explain what someone doesn’t need before starting (expensive gear, a big audience, perfect skills) and what they do need.", "Static post or Reel", "Save this for the day you doubt yourself."),
            ("A Reminder for Beginners", "Write a short, original note to people who are just starting out in your niche.", "Text-only static post", "Send this to someone who’s just starting."),
            ("What 15 Minutes a Day Can Do", "Show realistically what a small daily habit can build over a few months, with your own example.", "Carousel", "What could you do with 15 minutes a day?"),
            ("A Customer’s Journey", "Share a customer’s progress story (with permission), focusing on their effort and decisions.", "Carousel", "Your story could be next — tell me where you’re starting."),
            ("The Long Game", "Talk honestly about what consistency looked like for you — the slow months included.", "Long caption or LinkedIn post", "How long have you been working on your goal?"),
            ("What a Setback Taught Me", "Describe a setback and the practical lesson you took from it.", "Talking-head Reel", "What’s a setback that helped you grow?"),
            ("A Note to My Past Self", "Write the advice you would give yourself on the day you started.", "Carousel or caption", "What would you tell your past self?"),
            ("Celebrating a Milestone", "Mark a milestone and thank the people who helped — including your audience.", "Static post or Reel", "Thank you for being here. Say hi below."),
            ("Weekend Reset", "Share a simple weekend reflection routine with three questions your audience can answer for themselves.", "Story sequence or carousel", "Save this for Sunday."),
        ],
    ),
    (
        "Behind the Scenes",
        "Show how things really get done. Behind-the-scenes content builds trust because it’s hard to fake.",
        [
            ("Workspace Tour", "Give a short tour of where you work and explain why it’s set up the way it is.", "Reel", "Show me your workspace — I’d love to see it."),
            ("How a Post Gets Made", "Show your content process from idea to published post, sped up.", "Time-lapse Reel", "Want my full content process? Follow along."),
            ("Tools I Use Every Day", "Walk through the tools, apps or equipment you actually use daily and what each one does for you.", "Carousel", "Which tool would you add?"),
            ("Packing an Order or Delivering a Project", "Show the care that goes into delivering your product or service.", "Reel", "Ever wondered what happens after you order?"),
            ("My Planning Session", "Show how you plan your week or your content — whiteboard, notebook, calendar or app.", "Reel or carousel", "How do you plan your week?"),
            ("Outtakes and Bloopers", "Share the mistakes and failed takes from recent content.", "Reel", "Tell me I’m not the only one."),
            ("Meet the Team", "Introduce the people behind your brand — or show that you’re a one-person team and what that means.", "Carousel", "Say hi to the team in the comments."),
            ("Draft vs Final", "Show a first draft next to the finished version and explain the changes you made.", "Carousel", "Which version do you prefer?"),
            ("A Week in Numbers", "Share honest numbers from your week: hours worked, posts made, coffees, meetings, tasks finished.", "Static post or carousel", "What would your week look like in numbers?"),
            ("The Making of a Product", "Document how one product, service or offer was created — from the first idea to launch day.", "Carousel or Reel series", "Want to see more of the process?"),
        ],
    ),
    (
        "Problem / Solution",
        "Name a specific problem, then solve it. These posts show your expertise in the most useful way possible.",
        [
            ("If You’re Struggling with [PROBLEM]", "List three common causes of the problem and a fix for each.", "Carousel", "Which cause sounds most like you?"),
            ("Why Your Current Approach Isn’t Working", "Explain why a popular approach fails for many people and what to try instead.", "Reel", "Save this before you try again."),
            ("Fix It in 3 Steps", "Give a clear, three-step solution to one specific problem.", "Carousel or Reel", "Try step one today and let me know."),
            ("The Troubleshooting Guide", "Create an “if this happens, try this” guide for a common problem in your niche.", "Carousel", "Save this for the next time it happens."),
            ("The Hidden Cause", "Reveal the less obvious reason behind a problem people usually blame on something else.", "Talking-head Reel", "Did you know this was the cause?"),
            ("Wrong Fix vs Right Fix", "Show the solution most people try first, why it doesn’t last, and what works better.", "Carousel", "Which fix have you tried?"),
            ("The Budget Version", "Show how to solve a problem with no money or very little, next to the ideal version.", "Carousel", "Share this with someone on a tight budget."),
            ("The “No Time” Solution", "Offer a version of your advice for people with only a few minutes a day.", "Reel", "Busy? Save this one."),
            ("A Real Scenario, Solved", "Walk through a realistic situation step by step, showing how you would solve it.", "Carousel or LinkedIn post", "What would you have done differently?"),
            ("How to Prevent It", "Explain how to avoid a common problem before it starts, with simple preventive habits.", "Checklist carousel", "Save this to stay ahead of it."),
        ],
    ),
    (
        "List / Tips",
        "Lists are easy to create, easy to read and easy to save. Keep every item specific and genuinely useful.",
        [
            ("5 Tips for a Complete Beginner", "The five things you would tell someone on their first day in your niche.", "Carousel", "Save this and share it with a beginner."),
            ("7 Free Resources", "Free tools, guides, websites or communities that genuinely help with [TOPIC].", "Carousel", "Which one are you checking out first?"),
            ("3 Habits That Made the Difference", "The three habits that improved your results the most, with how you built each one.", "Reel or carousel", "Which habit could you start this week?"),
            ("10 Questions to Ask First", "Questions your audience should ask before making an important decision in your niche.", "Carousel", "Save this for your next big decision."),
            ("5 Things to Stop Doing", "Habits or methods your audience should drop, and what to do instead.", "Carousel", "Which one are you stopping today?"),
            ("4 Underrated Tips", "Tips that rarely get mentioned but make a real difference.", "Reel", "Did you know any of these?"),
            ("6 Ways to Use One Tool", "Show different, creative ways to use a single tool or product your audience already has.", "Carousel", "How else do you use it?"),
            ("5 Lessons from a Project", "Five takeaways from a recent project, book, event or experience.", "Carousel or LinkedIn post", "What’s the best lesson from your week?"),
            ("3 Signs You’re Ready", "Help your audience recognize when they’re ready to take the next step.", "Carousel", "How many signs do you see in yourself?"),
            ("The 5-Minute Version", "Five micro-actions that each take less than five minutes.", "Reel", "Pick one and do it right now."),
        ],
    ),
    (
        "Promotional",
        "Promotion works when it’s clear and honest. Aim for roughly one promotional post for every four or five value posts.",
        [
            ("Meet the Offer", "Introduce your product or service: what it is, who it’s for and the specific problem it solves.", "Carousel", "Questions? Send me a message."),
            ("Feature to Benefit", "Pick three features of your offer and explain what each one actually means for the customer.", "Carousel", "Find out more through the link in bio."),
            ("Customer Review Spotlight", "Share a real review, with context about the customer’s situation before they bought.", "Static post", "Read more reviews through the link in bio."),
            ("FAQ About the Offer", "Answer the five questions people ask most before buying.", "Carousel", "Have a different question? Ask below."),
            ("The Honest Objection", "Address one common hesitation directly and honestly, even if the answer is “this might not be for you”.", "Talking-head Reel", "Still unsure? Send me a message."),
            ("Who This Is Not For", "Clearly describe who shouldn’t buy, so the right people feel confident.", "Carousel or caption", "If this sounds like you, the link is in bio."),
            ("How It Works", "Explain the buying or working-together process in three simple steps.", "Carousel", "Ready to start? Link in bio."),
            ("Why I Created It", "Tell the story behind your offer and the problem you kept seeing that inspired it.", "Reel or carousel", "Learn more through the link in bio."),
            ("An Honest Deadline Reminder", "Remind your audience about a real deadline, price change or enrollment window.", "Story and static post", "Last chance — details in bio."),
            ("What You Can Realistically Expect", "Describe the result customers can expect, the effort it takes and how long it usually takes — without hype.", "Carousel", "Questions about fit? Message me."),
        ],
    ),
]
