"""File 09 — BONUS: 30 AI Image Prompts.

Each category: (title, [(prompt title, prompt, best for, tip)]).
"""

GLOSSARY = {
    "PRODUCT": "The item you want to show — “a ceramic coffee mug”, “a skincare serum bottle”.",
    "BRAND": "Your brand’s personality in a few words — “calm and natural”, “bold and playful”.",
    "COLOR": "A color or palette — “sage green and cream”, “deep navy with brass accents”.",
    "STYLE": "A visual style — “clean editorial”, “warm film photography”, “flat illustration”.",
    "SETTING": "Where the scene takes place — “a small home office”, “a sunlit café”.",
    "SUBJECT": "The main person or object — describe clothing, age range or materials generally.",
    "FOOD": "A dish or drink — “a bowl of ramen”, “an iced matcha latte”.",
    "OUTFIT": "Clothing described by type, color and material — no brand names.",
    "SEASON": "Spring, summer, autumn or winter — or a mood like “rainy afternoon”.",
    "ASPECT RATIO": "4:5 for Instagram feed, 9:16 for Stories and Reels, 1:1 for square, 16:9 for YouTube.",
}

CATEGORIES = [
    (
        "Business",
        [
            ("Focused Work Session",
             "A professional working at a tidy wooden desk in [SETTING], viewed from a 45-degree angle, laptop open with an unreadable blurred screen, notebook and pen beside it, soft natural window light from the left, calm and focused mood, accents of [COLOR], [STYLE] photography, shallow depth of field, plenty of empty space on the right side for text, [ASPECT RATIO].",
             "Carousel covers, LinkedIn posts, blog headers",
             "Asking for empty space gives you room to add a headline in Canva."),
            ("Strategy Whiteboard",
             "Close-up of a whiteboard covered in hand-drawn diagrams, arrows and sticky notes in [COLOR], a hand holding a marker in the foreground, slightly out of focus, bright modern office, daylight, [STYLE] photography, no readable text, [ASPECT RATIO].",
             "Planning and strategy content",
             "AI often produces garbled lettering, so ask for “no readable text” and add your own."),
            ("Small Business Owner Portrait",
             "Environmental portrait of a small business owner standing in their [SETTING], arms relaxed, warm and confident expression, natural light, background softly blurred but recognizable, color palette inspired by [COLOR], [BRAND] mood, [STYLE] photography, [ASPECT RATIO].",
             "About posts, brand stories, website visuals",
             "Use AI portraits as mood references or illustrations — your audience will want to see the real you."),
        ],
    ),
    (
        "Productivity",
        [
            ("Flat-Lay Planning Setup",
             "Top-down flat lay of a weekly planner, a cup of coffee, a pen, a phone face down and a small plant arranged on a [COLOR] surface, neat grid composition, soft diffused daylight, minimal shadows, [STYLE] photography, generous negative space in the top third, [ASPECT RATIO].",
             "Weekly planning posts, Monday content",
             None),
            ("Deep Work Mood",
             "Moody scene of a single desk lamp lighting a notebook and laptop in an otherwise dark room, late evening, warm tungsten light against cool [COLOR] shadows, cinematic atmosphere, [STYLE], quiet and focused feeling, [ASPECT RATIO].",
             "Focus tips, routines, late-night work content",
             None),
            ("Morning Routine Moment",
             "Soft morning scene of [SUBJECT] writing in a journal next to a window, steam rising from a mug, sheer curtains, golden-hour light, calm and unhurried mood, muted palette with touches of [COLOR], [STYLE] photography, [ASPECT RATIO].",
             "Habit, routine and mindset posts",
             None),
        ],
    ),
    (
        "Lifestyle",
        [
            ("Café Work Scene",
             "A relaxed person working on a laptop at a small table in a sunlit café, latte on the table, plants and natural textures in the background, candid composition, warm light, [COLOR] tones, [STYLE] photography, lifestyle feel, [ASPECT RATIO].",
             "Remote work, freelancing and lifestyle content",
             None),
            ("Cozy Seasonal Corner",
             "A cozy reading corner styled for [SEASON], armchair with a knitted blanket, stack of books, warm lamp, a hot drink on a side table, soft textures, [COLOR] color palette, [STYLE] interior photography, inviting mood, [ASPECT RATIO].",
             "Seasonal posts, slow-living and home content",
             None),
            ("Weekend Walk",
             "Candid photo of [SUBJECT] walking along a tree-lined path on a [SEASON] morning, seen from behind, soft sunlight through the leaves, natural colors with hints of [COLOR], [STYLE] photography, sense of calm and freedom, [ASPECT RATIO].",
             "Mindset posts, rest and balance content",
             None),
        ],
    ),
    (
        "Technology",
        [
            ("Clean Tech Desk",
             "Minimal desk setup with a laptop, wireless keyboard, headphones and a phone on a stand, cable-free, [COLOR] accent lighting on the wall behind, modern and clean, [STYLE] product photography, even soft light, no logos, [ASPECT RATIO].",
             "Tech tips, tool roundups, productivity apps",
             "Add “no logos” to avoid accidental brand marks."),
            ("Abstract AI Concept",
             "Abstract visual representing artificial intelligence: flowing lines of light forming a network, soft glowing nodes, deep dark background with [COLOR] highlights, elegant and calm rather than futuristic-cliché, [STYLE] 3D render, room for a headline in the center, [ASPECT RATIO].",
             "Posts about AI, automation and digital tools",
             None),
            ("Hands on Phone",
             "Close-up of hands holding a smartphone, the screen showing a soft blurred interface, background softly out of focus in [SETTING], natural light, [COLOR] tones, [STYLE] photography, relatable everyday feel, [ASPECT RATIO].",
             "Social media tips, app tutorials",
             "Place your own screenshot onto the phone screen in Canva."),
        ],
    ),
    (
        "Fashion",
        [
            ("Outfit Editorial",
             "Full-body editorial photo of a model wearing [OUTFIT], standing against a plain [COLOR] backdrop, confident relaxed pose, soft studio lighting, [STYLE] fashion photography, clean and modern, [ASPECT RATIO].",
             "Outfit ideas, styling tips, fashion brands",
             None),
            ("Fabric Detail Close-Up",
             "Macro close-up of the texture of [OUTFIT] — visible weave, stitching and folds, side lighting to emphasize texture, [COLOR] palette, [STYLE] photography, tactile and premium feel, [ASPECT RATIO].",
             "Product quality, materials and craftsmanship posts",
             None),
            ("Capsule Wardrobe Flat Lay",
             "Neatly arranged flat lay of a capsule wardrobe: [OUTFIT] pieces, shoes and two accessories on a [COLOR] background, balanced spacing, soft even light, [STYLE] photography, no brand labels visible, [ASPECT RATIO].",
             "Capsule wardrobe, packing lists, style guides",
             None),
        ],
    ),
    (
        "Food",
        [
            ("Overhead Dish Shot",
             "Overhead photo of [FOOD] in a handmade ceramic bowl on a rustic table, a linen napkin and cutlery placed beside it, scattered fresh ingredients, natural side light, [COLOR] props, [STYLE] food photography, appetizing and fresh, [ASPECT RATIO].",
             "Recipes, menus, restaurant and café posts",
             None),
            ("Drink Close-Up",
             "Close-up of [FOOD] in a clear glass, condensation on the glass, ice and garnish visible, blurred café background, backlit by soft daylight, [COLOR] tones, [STYLE] beverage photography, refreshing mood, [ASPECT RATIO].",
             "Drinks menus, seasonal specials",
             None),
            ("Cooking in Action",
             "Action shot of hands preparing [FOOD] in a home kitchen, flour or steam in the air, motion slightly frozen, warm light, wooden surfaces with [COLOR] accents, [STYLE] photography, authentic and homemade feel, [ASPECT RATIO].",
             "Cooking tutorials, behind-the-scenes, food brands",
             None),
        ],
    ),
    (
        "Personal Brand",
        [
            ("Signature Brand Background",
             "Elegant abstract background for a personal brand that feels [BRAND], soft gradient of [COLOR], subtle paper or grain texture, gentle organic shapes, lots of empty space, [STYLE], suitable for quote graphics, [ASPECT RATIO].",
             "Quote posts, carousel backgrounds, Story templates",
             "Generate once, then reuse it as a consistent background across posts."),
            ("Creator at Work",
             "Candid photo of [SUBJECT] recording a video with a phone on a small tripod in [SETTING], soft daylight from a nearby window, natural expression mid-sentence, [COLOR] accents in the room, [STYLE] photography, authentic behind-the-scenes feel, [ASPECT RATIO].",
             "Content creation, personal brand and coaching posts",
             None),
            ("Branded Workspace Detail",
             "Detail shot of a branded workspace: notebook, business cards with no readable text, a pen and a small object that reflects a [BRAND] personality, arranged on a [COLOR] desk, soft daylight, [STYLE] photography, [ASPECT RATIO].",
             "Brand reveals, about posts, announcements",
             None),
        ],
    ),
    (
        "Minimalist",
        [
            ("Single Object Still Life",
             "Minimalist still life of a single [PRODUCT] on a plain [COLOR] surface, long soft shadow, strong negative space, centered composition, [STYLE], calm and refined, [ASPECT RATIO].",
             "Quote posts, product teasers, announcements",
             None),
            ("Architectural Lines",
             "Minimalist architectural photograph of clean white walls, a curved staircase and soft shadows, single accent of [COLOR], geometric composition, bright daylight, [STYLE] photography, quiet and elegant, [ASPECT RATIO].",
             "Background images for text-heavy posts",
             None),
            ("Paper Texture Background",
             "Top-down photo of textured handmade paper in [COLOR], subtle natural fibers, soft even lighting, no objects, no text, [STYLE], perfect as a background for typography, [ASPECT RATIO].",
             "Carousel backgrounds, quote graphics",
             None),
        ],
    ),
    (
        "Product Photography",
        [
            ("Clean Studio Packshot",
             "Professional studio packshot of [PRODUCT] on a seamless [COLOR] background, soft key light with a subtle reflection beneath, crisp details, centered, [STYLE] product photography, e-commerce quality, [ASPECT RATIO].",
             "Product launches, shop listings, ads",
             "For real listings, photograph your actual product — use AI shots for mood and concept."),
            ("Lifestyle Product Scene",
             "[PRODUCT] placed naturally in [SETTING], used in everyday life, props that match a [BRAND] personality, natural window light, [COLOR] palette, [STYLE] photography, the product is clearly the hero of the image, [ASPECT RATIO].",
             "Product promotion, use-case posts",
             None),
            ("Product with Ingredients or Materials",
             "[PRODUCT] surrounded by the raw materials or ingredients it is made from, arranged in an artful composition on a [COLOR] surface, soft directional light, [STYLE] photography, premium and transparent feel, [ASPECT RATIO].",
             "Behind-the-product, quality and ingredient posts",
             None),
        ],
    ),
    (
        "Editorial",
        [
            ("Magazine-Style Portrait",
             "Editorial magazine-style portrait of [SUBJECT] in [SETTING], strong but soft directional light, thoughtful expression, [COLOR] color grading, [STYLE] editorial photography, space at the top for a headline, [ASPECT RATIO].",
             "Interviews, features, thought-leadership posts",
             None),
            ("Conceptual Editorial Illustration",
             "Conceptual editorial illustration representing [SUBJECT] as a visual metaphor, simple shapes, limited palette of [COLOR] and off-white, [STYLE] illustration, clever and clean, suitable for an article header, [ASPECT RATIO].",
             "Opinion posts, newsletters, blog headers",
             "Metaphors work well: “a person climbing a stack of books” for learning, for example."),
            ("Documentary Moment",
             "Documentary-style photograph capturing a real-feeling moment in [SETTING], natural light, slight film grain, candid composition, muted [COLOR] tones, [STYLE], honest and human, [ASPECT RATIO].",
             "Storytelling posts, community and culture content",
             None),
        ],
    ),
]
