"""File 02 — 100 AI Prompts.

Each category: (title, description, [(prompt title, prompt text, optional tip)]).
Customization fields are derived from the [PLACEHOLDERS] in each prompt, so
the "Customize" line can never drift out of sync with the prompt itself.
"""

GLOSSARY = {
    "NICHE": "Your field, as specifically as possible — “home workouts for busy parents”, not “fitness”.",
    "TARGET AUDIENCE": "The person you’re talking to — “first-time freelance designers”, “café owners in small towns”.",
    "TOPIC": "The subject of this one piece of content.",
    "PRODUCT/SERVICE": "What you sell, in one line — “a 4-week beginner yoga course”, “bookkeeping for freelancers”.",
    "PLATFORM": "Instagram, TikTok, LinkedIn, Facebook, YouTube…",
    "TONE": "How you want to sound — friendly, direct, calm, playful, expert, warm.",
    "GOAL": "What this content should achieve — saves, comments, shares, follows, clicks, sales.",
    "PROBLEM": "A specific struggle your audience has.",
    "RESULT": "An outcome your audience wants.",
    "STORY": "A few honest sentences describing something that happened.",
    "MONTH": "The month you’re planning for.",
    "TREND": "A format or trend you’ve noticed, described in a sentence.",
    "PASTE CONTENT": "Paste your existing text, script, transcript, list or notes here.",
    "EVENT": "A launch, sale, workshop, opening, milestone or announcement.",
    "COMMENT": "A real comment or question you received.",
    "CLAIM": "A common belief or piece of advice in your niche.",
    "CATEGORY": "A group of things you can rank — tools, habits, apps, methods.",
    "DESCRIBE IMAGE": "A plain description of the photo or visual you’re posting.",
    "NUMBER": "How many you want.",
}

CATEGORIES = [
    (
        "Content Ideas",
        "Never start from a blank page again. These prompts turn your niche into a steady supply of specific, useful ideas.",
        [
            ("Generate Content Ideas",
             "You are a social media strategist specializing in [NICHE]. Generate 20 content ideas for [TARGET AUDIENCE]. Divide them into educational, entertaining, inspirational and promotional content. Make each idea specific and practical — no vague topics like “tips for success”. For each idea, add the best format (Reel, carousel, static post or Story) in brackets.",
             "Run it again with a different audience segment to get a fresh batch."),
            ("Mine Audience Questions",
             "Act as an experienced [NICHE] professional who has answered hundreds of beginner questions. List 25 questions that [TARGET AUDIENCE] commonly ask about [TOPIC] — including the ones they might be too embarrassed to ask out loud. Group them by stage: just curious, getting started, and stuck. For each question, suggest a one-line post angle.",
             None),
            ("Map Audience Pain Points",
             "You are a customer research specialist. For [TARGET AUDIENCE] in [NICHE], list 10 frustrations they feel before they start, 10 while they are trying, and 10 when progress stalls. Write each frustration in the words the audience would use, not industry jargon. Then turn the 5 most common frustrations into content ideas.",
             None),
            ("Find Myths to Correct",
             "List 15 common myths or misunderstandings about [TOPIC] in [NICHE]. For each one, explain in one sentence why people believe it and in one sentence what is closer to the truth. Mark any point that I should fact-check before posting. Finish with 5 post ideas based on the strongest myths.",
             "Always verify the “truth” side yourself before publishing."),
            ("Build a Beginner-to-Advanced Ladder",
             "Create a content ladder about [TOPIC] for [TARGET AUDIENCE]: 6 ideas for complete beginners, 6 for people with some experience, and 6 for advanced learners. Each idea should build on the previous level. Give every idea a working title and a one-sentence summary.",
             None),
            ("Define Content Pillars",
             "You are a content strategist. My niche is [NICHE], my audience is [TARGET AUDIENCE], and I sell [PRODUCT/SERVICE]. Suggest 4 content pillars that would build trust and naturally lead toward my offer. For each pillar, explain its purpose in one sentence and list 5 specific post ideas.",
             None),
            ("Plan Seasonal Content",
             "Suggest 12 content ideas for [NICHE] that fit naturally into [MONTH]. Consider seasons, holidays, school or work cycles, and the mood people are typically in at that time of year. Avoid forced holiday tie-ins. For each idea, give the best posting week and format.",
             None),
            ("Adapt a Trend to Your Niche",
             "Here is a trend or format I’ve noticed: [TREND]. Suggest 5 ways to adapt it for [NICHE] so it still feels relevant to [TARGET AUDIENCE]. For each version, explain the twist in one sentence and describe exactly what I would film or design.",
             None),
            ("Generate Honest Opinions",
             "List 10 honest, defensible opinions about [NICHE] that some of [TARGET AUDIENCE] might disagree with. Avoid anything offensive, personal or impossible to back up. For each opinion, add a short reason and a question I could ask my audience to start a respectful discussion.",
             "Only post opinions you actually hold — your audience will ask follow-up questions."),
            ("Behind-the-Scenes Ideas",
             "I run a business selling [PRODUCT/SERVICE]. Give me 15 behind-the-scenes content ideas that show my process, tools, workspace and decision-making without revealing anything confidential. For each idea, describe what to film or photograph in one sentence.",
             None),
            ("Find Underserved Angles",
             "Here are topics that creators in my niche post about constantly: [PASTE CONTENT]. Suggest 10 angles on the same subjects that are rarely covered — more specific, more honest, or aimed at an overlooked segment of [TARGET AUDIENCE]. Explain why each angle stands out.",
             None),
            ("Turn Customer Questions into Posts",
             "Here are questions my customers and followers have asked me: [PASTE CONTENT]. Turn each one into a content idea. For every idea, give a working title, the best format, and the one key point the post must make.",
             None),
            ("Explore One Topic from 10 Angles",
             "Take the topic [TOPIC] and create 10 different content ideas from it using these angles: how-to, common mistake, personal story, myth, comparison, checklist, tool or resource, opinion, case study, and question for the audience. Write one working title per angle.",
             "This is the fastest way to fill a week from a single subject."),
            ("Create a Recurring Series",
             "Suggest 5 recurring content series for [NICHE] that I could post weekly. For each series, give a short memorable name, the format, what one episode contains, and 4 episode ideas to start with. Keep each series realistic for one person to produce.",
             None),
            ("Plan an Educational Mini-Series",
             "Break [TOPIC] into a 7-part educational series for [TARGET AUDIENCE]. Each part should teach one clear idea and end with a reason to watch or read the next part. Give each part a title, the key takeaway, and a suggested format.",
             None),
            ("Generate Comparison Posts",
             "List 10 “A vs B” comparisons that [TARGET AUDIENCE] in [NICHE] genuinely wonder about — methods, tools, approaches or habits. For each comparison, explain who option A suits better and who option B suits better. Keep it balanced, not salesy.",
             None),
            ("Build Your Story Bank",
             "Act as a friendly interviewer helping me find stories for my content. Ask me 15 questions, one at a time, about my experience in [NICHE] — first attempts, mistakes, turning points, customers and lessons. After I answer all of them, summarize the 10 stories with the most content potential.",
             "Answer out loud with voice typing — it’s faster and sounds more like you."),
            ("Write Engagement Questions",
             "Write 20 questions I can ask [TARGET AUDIENCE] about [TOPIC] to start conversations. Mix formats: this-or-that, fill-in-the-blank, quick opinions, and personal experience. Keep each question short enough to fit on a single slide or Story.",
             None),
            ("Product-Led Content Ideas",
             "I sell [PRODUCT/SERVICE] to [TARGET AUDIENCE]. Suggest 10 content ideas that demonstrate its value through education, examples or results — without sounding like an advert. For each idea, explain how it naturally connects back to the offer.",
             None),
            ("Prioritize Your Ideas",
             "Here is my list of content ideas: [PASTE CONTENT]. Score each idea from 1 to 5 on relevance to [TARGET AUDIENCE], ease of creation, and potential to start a conversation. Return a ranked table, then recommend the 5 ideas I should create this week and explain why.",
             None),
        ],
    ),
    (
        "Instagram Posts",
        "Carousels, single images and Story sequences — structured, on-brand and ready to design.",
        [
            ("7-Slide Educational Carousel",
             "You are an Instagram content strategist. Create a 7-slide carousel about [TOPIC] for [TARGET AUDIENCE]. Slide 1: a hook of 8 words or fewer. Slides 2–6: one idea per slide with a short headline and a maximum of 25 words of supporting text. Slide 7: a summary and a call to action to [GOAL]. Tone: [TONE].",
             "Keep slide text short — the caption can carry the detail."),
            ("Mistakes Carousel",
             "Create a carousel titled “5 mistakes [TARGET AUDIENCE] make with [TOPIC]”. For each mistake, write the mistake as a short headline, one sentence on why it happens, and one sentence on the fix. Add a cover slide and a final slide that invites people to save the post.",
             None),
            ("Step-by-Step Tutorial Carousel",
             "Write a step-by-step carousel that teaches [TARGET AUDIENCE] how to [RESULT]. Use 5 to 7 steps. Each step needs a verb-first headline (for example, “Choose one platform”) and one or two short supporting lines. Include one common pitfall to avoid on the final step.",
             None),
            ("Myth vs Fact Carousel",
             "Create a myth-vs-fact carousel about [TOPIC] for [NICHE]. Include 4 myths. For each, write the myth in the audience’s words, then the fact in one clear sentence, then a short practical takeaway. Flag any fact I should double-check before posting.",
             None),
            ("Save-Worthy Checklist Post",
             "Create a checklist post for [TARGET AUDIENCE] titled “Before you [TOPIC], check these”. Include 8 checklist items, each under 10 words, ordered by priority. Then write a short caption explaining when to use the checklist and asking people to save it.",
             None),
            ("Original Insight Graphics",
             "Write 6 original, single-sentence insights about [TOPIC] that would work as text-only Instagram graphics for [TARGET AUDIENCE]. Each sentence must be under 15 words, specific and in my own voice — not a famous quote or a generic motivational line. Add a two-line caption for each one.",
             None),
            ("Before/After Carousel",
             "Create a before/after carousel showing how [TARGET AUDIENCE] can go from [PROBLEM] to [RESULT]. Slide 1: a hook. Slides 2–3: the “before” situation in specific, relatable detail. Slides 4–6: what changed and how. Final slide: a realistic expectation and a call to action. Avoid exaggerated promises.",
             None),
            ("Personal Story Carousel",
             "Turn this experience into an 8-slide story carousel: [STORY]. Slide 1 should create curiosity without giving away the ending. Use short sentences, one moment per slide, and finish with the lesson and a question for the audience. Keep it honest and specific.",
             None),
            ("Feature-to-Benefit Carousel",
             "I sell [PRODUCT/SERVICE] to [TARGET AUDIENCE]. List its 5 main features, then translate each feature into a clear benefit the customer actually cares about. Turn this into a 7-slide carousel with a problem-focused cover slide and a soft call to action at the end.",
             None),
            ("Tools and Resources Post",
             "Create a carousel listing 6 tools or resources that help [TARGET AUDIENCE] with [TOPIC]. For each, write what it is, what it’s best for, and one honest limitation. Suggest the type of tool for each slide (for example, “a free planning app”), but leave the brand names out — I will fill in only tools I have actually used.",
             "Never recommend a tool you haven’t tried. Your credibility is the product."),
            ("This-or-That Engagement Post",
             "Write 8 this-or-that pairs for [TARGET AUDIENCE] about [TOPIC]. Each pair should reveal something about the audience’s preferences or habits. Then write a caption that invites people to answer in the comments and explains why I’m asking.",
             None),
            ("Testimonial Post",
             "Here is feedback from a customer: [PASTE CONTENT]. Turn it into a testimonial post. Pull out the strongest one-sentence quote for the graphic, then write a caption that explains the customer’s situation before, what they did, and what changed. Keep the customer’s words unedited and avoid adding claims they didn’t make.",
             "Ask the customer for permission before you post their words."),
            ("Announcement Post",
             "Write an Instagram announcement for [EVENT]. Include a headline for the graphic (under 8 words), a caption that explains what it is, who it’s for, when it happens, and what people should do next. Tone: [TONE]. Keep the caption under 120 words.",
             None),
            ("Interactive Story Sequence",
             "Plan a 6-frame Instagram Story sequence about [TOPIC] for [TARGET AUDIENCE]. Include one poll, one quiz or slider, and one question box. For each frame, write the on-screen text (maximum 15 words) and describe the background visual.",
             None),
            ("Instagram Bio Rewrite",
             "Rewrite my Instagram bio. I help [TARGET AUDIENCE] with [RESULT] through [PRODUCT/SERVICE]. Give me 5 versions under 150 characters. Each should make it clear who I help and what they get, include a reason to tap the link, and avoid buzzwords like “passionate”, “guru” or “empowering”.",
             None),
        ],
    ),
    (
        "Reels / Short Videos",
        "Scripts, shot lists and on-screen text for short vertical video — talking-head and faceless.",
        [
            ("30-Second Educational Reel",
             "Write a 30-second Reel script teaching [TARGET AUDIENCE] about [TOPIC]. Structure: a hook in the first line (under 10 words), 3 quick points, and a closing call to action to [GOAL]. Write the spoken script and the on-screen text separately. Use short, natural sentences that sound good out loud.",
             "Read it aloud once before filming — cut any word you stumble on."),
            ("10 Hook Variations",
             "I’m making a short video about [TOPIC] for [TARGET AUDIENCE]. Write 10 different opening lines, each under 12 words. Use a mix of curiosity, a bold statement, a mistake, a question and a quick result. Rank them from strongest to weakest and explain the top choice in one sentence.",
             None),
            ("Talking-Head Tips Reel",
             "Write a 45-second talking-head script: “3 [TOPIC] tips I’d give a complete beginner”. Each tip needs one sentence of explanation and one quick example. Add simple filming notes: where to cut, when to add on-screen text, and when to change the camera angle.",
             None),
            ("Faceless Reel Script",
             "Create a faceless Reel about [TOPIC] for [NICHE]. Provide a shot list of 6–8 B-roll clips I can film with a phone (hands, workspace, screen, objects), the on-screen text for each clip, and an optional voiceover script. Total length: 15–25 seconds.",
             None),
            ("Common Mistake Reel",
             "Write a Reel script about one common mistake [TARGET AUDIENCE] make with [TOPIC]. Show the mistake, explain why it’s a problem in one sentence, then demonstrate or describe the better approach. End with a line that invites people to share it with someone who needs it. Maximum 40 seconds.",
             None),
            ("Day-in-the-Life Reel",
             "Plan a 30-second day-in-the-life Reel for someone working in [NICHE]. List 8 short clips in chronological order with a one-line caption for each. Include one honest, unglamorous moment. Suggest the on-screen text for the opening and closing clips.",
             None),
            ("How-To Tutorial Reel",
             "Create a tutorial Reel script that shows [TARGET AUDIENCE] how to [RESULT] in under 60 seconds. Break it into numbered steps with a clear visual for each. Include on-screen text, the spoken line for each step, and a final shot that shows the finished result.",
             None),
            ("Myth-Busting Reel",
             "Write a myth-busting Reel about this claim: [CLAIM]. Open by stating the claim as many people say it, then explain what’s actually true in plain language, and give one practical action. Keep the tone respectful, not mocking. Length: 30–45 seconds.",
             "Back up the correction with a source you trust, and mention it in the caption."),
            ("Storytime Reel",
             "Turn this story into a 45–60 second Reel script: [STORY]. Open in the middle of the action, keep the setup to two sentences, build to the turning point, and end with the lesson in one line. Add on-screen text for the first 3 seconds that makes people want to stay.",
             None),
            ("Product Demo Reel",
             "Write a 30-second demo Reel for [PRODUCT/SERVICE]. Start with the problem it solves (as the customer would describe it), show it in use in 3 quick steps, and end with the result and a soft call to action. List the shots I need and the on-screen text for each.",
             None),
            ("Text-on-Screen Reel",
             "I want to create a 7–10 second Reel using a short audio track and text on screen. Write 10 different text overlays about [TOPIC] for [TARGET AUDIENCE] — relatable, specific and readable in under 4 seconds. For each one, suggest a simple visual to film behind the text.",
             None),
            ("Reaction-Style Reel",
             "I want to react to a common belief in [NICHE]: [CLAIM]. Write a 30-second script for a green-screen or split-screen video. Show the belief, give my honest reaction, explain my reasoning with one example, and invite viewers to share their view.",
             None),
            ("B-Roll Shot List",
             "Create a list of 20 B-roll shots I can film at home or at my workspace to support videos about [NICHE]. Group them into hands and details, workspace, process, and lifestyle. Add one framing or lighting tip for each group.",
             "Film these in one session and you’ll have footage for weeks."),
            ("On-Screen Text and Captions",
             "Here is my video script: [PASTE CONTENT]. Break it into on-screen text overlays of no more than 7 words each, timed to the key moments. Then write a caption of under 100 words and a list of 5 keyword phrases to include naturally in the caption.",
             None),
            ("5-Part Reel Series",
             "Plan a 5-part Reel series about [TOPIC] for [TARGET AUDIENCE]. Give the series a name, write a hook for each episode, list the key point of each, and write a closing line for every episode that sets up the next one.",
             None),
        ],
    ),
    (
        "TikTok",
        "Fast, native-feeling TikTok concepts: replies, POVs, multi-part stories and quick tutorials.",
        [
            ("Pattern-Interrupt TikTok Script",
             "Write a TikTok script about [TOPIC] for [TARGET AUDIENCE]. The first 2 seconds must interrupt the scroll with a surprising statement or visual action. Keep the total under 35 seconds, use casual spoken language, and end with a question that invites comments.",
             None),
            ("Reply-to-Comment Video",
             "A follower left this comment: [COMMENT]. Write a 30–45 second reply video script. Start by reading the comment out loud, give a clear and helpful answer with one example, and finish by asking what others would add. Keep the tone friendly even if the comment was critical.",
             "Reply videos are an easy way to show you listen — and they’re quick to film."),
            ("POV Video Ideas",
             "Write 10 POV video concepts for [NICHE] that [TARGET AUDIENCE] would find relatable. For each, write the POV line for the on-screen text and describe what happens in the video in 2 sentences. Keep them light, specific and easy to film alone.",
             None),
            ("Things I Wish I Knew",
             "Write a TikTok script: “Things I wish I knew before starting [TOPIC]”. Include 4 points, each with a short personal-sounding explanation. Keep sentences short and conversational. Add on-screen text for each point and a closing line that invites people to share their own.",
             None),
            ("Respond to a Popular Claim",
             "Write a 40-second TikTok script responding to this popular claim: [CLAIM]. Acknowledge why people believe it, give a more complete answer, and share a practical alternative. The tone should be confident and fair — no mocking the original creator.",
             None),
            ("3-Part Storytime",
             "Turn this story into a 3-part TikTok series: [STORY]. Each part should be 30–45 seconds and end at a natural cliffhanger. Write the script for each part, an on-screen title for each (“Part 1: …”), and the first line of each follow-up so new viewers aren’t lost.",
             None),
            ("Ranking Video",
             "Create a ranking video script where I rank 5 [CATEGORY] for [TARGET AUDIENCE] from least to most useful. For each item, give a one-sentence reason. Keep my reasoning clear and fair so viewers who disagree want to comment rather than scroll away.",
             None),
            ("20-Second Quick Tutorial",
             "Write a 20-second TikTok tutorial showing [TARGET AUDIENCE] how to [RESULT]. Use 3 steps maximum, one sentence per step, and on-screen text that works without sound. End with the finished result on screen.",
             None),
            ("TikTok Captions",
             "Write 6 TikTok captions for a video about [TOPIC]. Each caption should be under 150 characters, add context the video doesn’t show, and naturally include a searchable phrase someone in [NICHE] might type. Suggest 4 relevant hashtags for each: two broad and two specific.",
             None),
            ("10-Minute TikTok Ideas",
             "Give me 12 TikTok ideas for [NICHE] that I can film in under 10 minutes with only my phone and no editing beyond trimming. For each, describe the concept, the setup, and the first line I should say.",
             "Keep this list for low-energy days. Consistency beats perfection."),
        ],
    ),
    (
        "LinkedIn",
        "Professional posts that build authority without sounding stiff — lessons, frameworks, case studies and profile copy.",
        [
            ("Lesson-Learned Post",
             "Write a LinkedIn post about a lesson I learned in [NICHE]: [STORY]. Open with a single line that states the lesson in a surprising way. Keep paragraphs to 1–2 sentences, include one specific detail, and end with a question for my network. Maximum 200 words. No hashtags in the body.",
             None),
            ("Respectful Contrarian Post",
             "Write a LinkedIn post challenging this common advice in [NICHE]: [CLAIM]. State what most people say, explain where it falls short with a concrete example, and offer a more useful approach. Stay professional and avoid attacking anyone. Maximum 220 words.",
             None),
            ("Framework Post",
             "Create a simple framework for helping [TARGET AUDIENCE] achieve [RESULT]. Give it a short, memorable name, 3–5 steps with one-sentence explanations, and a brief example of it in action. Format it as a LinkedIn post with clean line breaks.",
             "Use the framework name consistently — it becomes something people associate with you."),
            ("Case Study Post",
             "Write a LinkedIn case study using these details: [PASTE CONTENT]. Structure it as situation, challenge, what we did, and result. Use specific numbers only if they appear in my details — do not invent any. End with the key lesson for [TARGET AUDIENCE].",
             "Get the client’s permission, or anonymize the details."),
            ("Milestone Post Without Bragging",
             "Help me share this milestone on LinkedIn: [EVENT]. Write a post that focuses on what I learned, who helped, and what it means for the people I serve — not just the achievement. Keep it humble, specific and under 180 words.",
             None),
            ("LinkedIn Document Carousel",
             "Create an 8-page LinkedIn document carousel about [TOPIC] for [TARGET AUDIENCE]. Page 1: a clear promise. Pages 2–7: one insight per page with a headline and up to 30 words. Page 8: a summary and an invitation to connect. Then write the accompanying post text in under 120 words.",
             None),
            ("Industry Observation Post",
             "Write a LinkedIn post sharing an observation about how [NICHE] is changing. Describe the change in plain language, give one example I’ve likely seen in my work, explain what it means for [TARGET AUDIENCE], and ask my network how they’re adapting. Avoid predictions stated as facts.",
             None),
            ("Conversation-Starter Post",
             "Write a short LinkedIn post that asks my network a thoughtful question about [TOPIC]. Give brief context on why I’m asking, share my own current answer in 2–3 sentences, and invite others to share theirs. Maximum 120 words.",
             None),
            ("Headline and About Section",
             "Rewrite my LinkedIn headline and About section. I help [TARGET AUDIENCE] achieve [RESULT] through [PRODUCT/SERVICE]. Write 3 headline options under 220 characters and one About section under 250 words that explains who I help, how, why I do it, and how to contact me. First person, no buzzwords.",
             None),
            ("Client Win to Post",
             "Turn this client result into a LinkedIn post: [PASTE CONTENT]. Give the credit to the client’s effort, explain the one or two things that made the biggest difference, and share a takeaway others can apply. Do not exaggerate the result or add details I didn’t provide.",
             None),
        ],
    ),
    (
        "Captions",
        "Captions that add context, sound like you and end with a clear next step.",
        [
            ("Caption from a Photo",
             "Write 3 caption options for an Instagram post. The image shows: [DESCRIBE IMAGE]. My audience is [TARGET AUDIENCE]. Option 1: short and witty. Option 2: a mini-story. Option 3: educational, with one useful tip. Each should end with a natural call to action.",
             None),
            ("Short Caption Pack",
             "Write 10 short captions (under 125 characters each) for posts about [TOPIC]. They should add context or personality rather than describe the image. Avoid clichés like “Let’s dive in” and “game-changer”.",
             None),
            ("Micro-Blog Caption",
             "Write a long-form Instagram caption (180–250 words) about [TOPIC] for [TARGET AUDIENCE]. Open with a one-line hook, tell a short relatable story or scenario, share 3 practical takeaways, and end with a question. Use line breaks for easy reading.",
             None),
            ("Caption Rewriter",
             "Here is my caption: [PASTE CONTENT]. Rewrite it 3 ways: clearer and shorter, warmer and more personal, and more direct with a stronger call to action. Keep my original meaning and any facts unchanged. Explain the main improvement in each version in one line.",
             "Pick the version that sounds most like you, then edit it by hand."),
            ("Soft-Sell Caption",
             "Write a caption that introduces [PRODUCT/SERVICE] to [TARGET AUDIENCE] without sounding pushy. Start with a problem they recognize, share a small insight or tip, then mention the offer as one option for people who want more help. Under 150 words.",
             None),
            ("Tone Switch",
             "Rewrite this caption in 3 tones — professional, friendly and playful: [PASTE CONTENT]. Keep the length similar and the message the same. Point out which words create each tone so I can learn to do it myself.",
             None),
            ("Carousel Caption",
             "Here is the text from my carousel slides: [PASTE CONTENT]. Write a caption that adds one extra insight not on the slides, explains who the carousel is for, and asks people to save it. Under 120 words.",
             None),
            ("Launch Countdown Captions",
             "Write 5 captions for the 5 days leading up to [EVENT]. Each caption should have a different purpose: announce, explain, answer a common question, show behind the scenes, and a final reminder. Keep each under 100 words with a clear next step.",
             None),
            ("Keywords and Hashtags",
             "I’m posting about [TOPIC] for [TARGET AUDIENCE] on [PLATFORM]. Suggest 6 keyword phrases people might search for that I can include naturally in my caption, and 10 hashtags split into broad, niche-specific and community tags. Only suggest relevant tags.",
             None),
            ("First-Line Tester",
             "Here is my caption: [PASTE CONTENT]. Write 10 alternative first lines that would make someone want to read the rest. Rank them, explain why the top 3 work, and point out any that sound like clickbait so I can avoid them.",
             None),
        ],
    ),
    (
        "Storytelling",
        "Structure your real experiences into content people remember — without inventing anything.",
        [
            ("Raw Memory to Structured Story",
             "Here is something that happened to me: [STORY]. Structure it as a short story post: a hook, the setup in 2 sentences, the problem or tension, the turning point, the lesson, and a question for the audience. Keep my details accurate and don’t add events that didn’t happen.",
             "The details only you know are what make a story believable — keep them in."),
            ("Origin Story",
             "Help me write my origin story for [NICHE]. Ask me 6 questions about why I started, what I was doing before, and what I wanted to change. After I answer, write a 200-word version for Instagram and a 120-word version for my website’s About page.",
             None),
            ("Failure Story",
             "Help me write a post about a failure: [STORY]. Be honest about what went wrong and my part in it, avoid self-pity, and focus on what I do differently now. End with one practical takeaway for [TARGET AUDIENCE]. Maximum 200 words.",
             None),
            ("Customer Journey Story",
             "Write an anonymized customer story using these details: [PASTE CONTENT]. Describe where the customer started, the moment they decided to change something, what they did, and where they are now. Make the customer the hero, not me. No invented results.",
             None),
            ("Then vs Now Story",
             "Write a “then vs now” post about my journey in [NICHE]. Then: [STORY]. Use specific, concrete comparisons (habits, tools, mindset, results) rather than vague statements. End with one piece of advice for someone at the “then” stage.",
             None),
            ("Teach with a Scenario",
             "Teach [TARGET AUDIENCE] about [TOPIC] through a short, relatable scenario. Create a fictional but realistic character, describe their situation in 3 sentences, show the mistake they make, and then show the better approach. Clearly frame it as an example, not a real case.",
             None),
            ("Brand Values Story",
             "My business values are [PASTE CONTENT]. For each value, suggest a short story or moment from running a business in [NICHE] that would show the value in action, rather than just stating it. Then write one full post based on the strongest idea.",
             None),
            ("Story in 5 Frames",
             "Turn this moment into a 5-frame Instagram Story sequence: [STORY]. Each frame needs on-screen text under 15 words and a suggested visual. Frame 1 hooks, frames 2–4 tell the moment, and frame 5 shares the lesson with a question sticker.",
             None),
            ("Extract Hooks from a Story",
             "Here is a longer story I’ve written: [PASTE CONTENT]. Write 10 different hooks that could open this story on social media. Base each one on a different moment or emotion from the story, and keep each under 12 words.",
             None),
            ("Organize a Story Bank",
             "Here is a list of experiences from my life and work: [PASTE CONTENT]. Sort them into story types: origin, failure, turning point, customer, behind the scenes, and lesson learned. For each one, suggest the content format and the main lesson it could teach [TARGET AUDIENCE].",
             None),
        ],
    ),
    (
        "Content Repurposing",
        "One good idea, many useful pieces. Turn what you’ve already made into new content for other formats and platforms.",
        [
            ("Article to Carousel",
             "Here is an article I wrote: [PASTE CONTENT]. Turn it into an 8-slide Instagram carousel. Pull out the most useful points, rewrite them as short slide headlines with supporting lines, and add a cover hook and a closing call to action.",
             None),
            ("Long Video to Short Clips",
             "Here is the transcript of my long video: [PASTE CONTENT]. Identify the 5 strongest moments that would work as standalone short clips. For each, quote the opening and closing lines, suggest a hook for on-screen text, and explain why it works on its own.",
             None),
            ("One Post, Five Platforms",
             "Here is a post that performed well: [PASTE CONTENT]. Adapt it for Instagram, TikTok, LinkedIn, Facebook and a YouTube Short. Change the format, length and tone to suit each platform rather than copying the same text. Present each version clearly labelled.",
             "Adapt, don’t copy-paste. Each platform has its own style."),
            ("Carousel to Reel",
             "Here is the text of my carousel: [PASTE CONTENT]. Turn it into a 30–45 second Reel script with a spoken hook, the key points in a natural speaking voice, on-screen text for each point, and a closing call to action.",
             None),
            ("Voice Note to LinkedIn Post",
             "Here is a transcript of a voice note where I talk through an idea: [PASTE CONTENT]. Turn it into a polished LinkedIn post that keeps my natural voice and phrasing. Remove filler words, tighten the structure, and keep the strongest line as the opening.",
             "Record ideas on walks — this prompt turns rambling into a finished post."),
            ("Weekly Newsletter from Posts",
             "Here are the posts I published this week: [PASTE CONTENT]. Turn them into a short email newsletter for [TARGET AUDIENCE]. Write a subject line, a personal opening, a summary of the most useful points, one extra insight not in the posts, and a single call to action.",
             None),
            ("Refresh an Old Post",
             "Here is one of my older posts: [PASTE CONTENT]. Write an updated version with a new angle, a fresh hook, and anything I’ve learned since. Suggest a different format from the original so it feels new to people who saw the first one.",
             None),
            ("Comments to FAQ Content",
             "Here are comments and questions from my recent posts: [PASTE CONTENT]. Group similar questions together, then turn the 5 most common groups into content ideas. For each, write a hook and the main answer in 2–3 sentences.",
             None),
            ("Carousel to Text Thread",
             "Turn this carousel content into a text thread for Threads or X: [PASTE CONTENT]. Write an opening post that works on its own, 5–7 follow-up posts with one idea each, and a final post that summarizes and asks a question.",
             None),
            ("Content Atomizer",
             "Here is one core idea: [TOPIC]. Create a full repurposing plan for one week. Include 1 long-form piece (article or video outline), 3 short video concepts, 3 Instagram post concepts, 3 Story frames, 1 LinkedIn post and 1 email. Give each piece a working title and a key message.",
             "Pair this with File 10 — the Content Repurposing System."),
        ],
    ),
]
