"""File 06 — Social Media Templates.

Each template is a dict:
  name, purpose, format, slides [(wireframe label, what goes on it)],
  copy [(slide, suggested copy)], visual [tips], cta, note (optional)
"""

TEMPLATES = [
    dict(
        name="Quote",
        purpose="Share one original insight in a single, save-worthy line. Good for quieter days and for reinforcing your point of view.",
        format="Single image · 1080 × 1350 px",
        slides=[("Quote", "One sentence, 20 words maximum, plus your name or handle.")],
        copy=[
            ("Graphic", "“[YOUR INSIGHT IN ONE SENTENCE]” — @yourhandle"),
            ("Example", "“Clarity beats creativity when nobody knows what you do yet.”"),
            ("Caption", "Two or three lines on why you believe this, plus one example from your work."),
        ],
        visual=[
            "Solid off-white or near-black background — nothing else competing.",
            "Large headline type (60–80 pt in Canva) with one key word in your accent color.",
            "Your handle small at the bottom, the same position every time.",
        ],
        cta="Save this if you needed the reminder today.",
        note="Use your own words. If you quote someone else, credit them by name.",
    ),
    dict(
        name="3 Tips",
        purpose="Teach three quick, practical actions on one topic. A reliable format for beginners and for busy weeks.",
        format="Carousel · 5 slides · 1080 × 1350 px",
        slides=[("Cover", "Promise of the three tips"), ("Tip 1", "Headline + one line"), ("Tip 2", "Headline + one line"), ("Tip 3", "Headline + one line"), ("CTA", "Recap + call to action")],
        copy=[
            ("Slide 1", "3 [TOPIC] tips I wish I’d known sooner"),
            ("Slide 2", "1. [TIP AS A VERB-FIRST HEADLINE] — [ONE-LINE EXPLANATION]"),
            ("Slide 3", "2. [TIP] — [WHY IT WORKS]"),
            ("Slide 4", "3. [TIP] — [QUICK EXAMPLE]"),
            ("Slide 5", "Which one will you try first? Save this for later."),
        ],
        visual=[
            "Large tip numbers (1, 2, 3) in your accent color, top left of each slide.",
            "Keep the same layout on slides 2–4 so the carousel feels designed.",
            "Maximum 25 words per slide.",
        ],
        cta="Which tip are you trying first?",
    ),
    dict(
        name="5 Mistakes",
        purpose="Help your audience avoid common errors. Mistake content invites self-checking, which makes people stop and read.",
        format="Carousel · 7 slides · 1080 × 1350 px",
        slides=[("Cover", "5 mistakes + audience"), ("Mistake 1", "Mistake → fix"), ("Mistake 2", "Mistake → fix"), ("Mistake 3", "Mistake → fix"), ("Mistake 4", "Mistake → fix"), ("Mistake 5", "Mistake → fix"), ("CTA", "Recap + save")],
        copy=[
            ("Slide 1", "5 mistakes [TARGET AUDIENCE] make with [TOPIC]"),
            ("Slides 2–6", "✕ [MISTAKE] / ✓ Instead: [BETTER APPROACH IN ONE SENTENCE]"),
            ("Slide 7", "Making one of these? You’re not alone. Save this and fix one at a time."),
        ],
        visual=[
            "Split each mistake slide in two: muted top half for the mistake, accent bottom half for the fix.",
            "Use a simple ✕ and ✓ icon — no clip-art.",
            "Number each slide so readers know how far they’ve come.",
        ],
        cta="Which mistake did you recognize? Tell me in the comments.",
    ),
    dict(
        name="Checklist",
        purpose="Give your audience a practical list they’ll come back to. Checklists are among the most saved formats.",
        format="Single image or 3-slide carousel · 1080 × 1350 px",
        slides=[("Cover", "Before you [ACTIVITY]…"), ("List", "6–8 checkbox items"), ("CTA", "Save + share")],
        copy=[
            ("Slide 1", "The [ACTIVITY] checklist: check these before you start"),
            ("Slide 2", "☐ [ITEM 1] ☐ [ITEM 2] ☐ [ITEM 3] … up to 8 items, each under 10 words"),
            ("Slide 3", "Save this for next time — and send it to someone who’s about to start."),
        ],
        visual=[
            "Real checkbox squares, left-aligned, generous line spacing.",
            "One accent color for the checkboxes only.",
            "Readable from a phone screen at arm’s length: minimum 32 pt in Canva.",
        ],
        cta="Save this checklist for your next [ACTIVITY].",
    ),
    dict(
        name="Educational Carousel",
        purpose="Teach a concept from problem to solution. Your core authority-building format.",
        format="Carousel · 7 slides · 1080 × 1350 px",
        slides=[("Hook", "Bold promise"), ("Problem", "Why it matters"), ("Idea", "The key concept"), ("Point 1", "Explain"), ("Point 2", "Explain"), ("Example", "Show it in action"), ("CTA", "Summary + action")],
        copy=[
            ("Slide 1", "[RESULT] is easier than you think — here’s how"),
            ("Slide 2", "Most people struggle with [PROBLEM] because [REASON]."),
            ("Slide 3", "The key idea: [CONCEPT IN ONE SENTENCE]"),
            ("Slides 4–5", "[POINT] — [SHORT EXPLANATION]"),
            ("Slide 6", "Example: [A SPECIFIC BEFORE/AFTER OR WORKED EXAMPLE]"),
            ("Slide 7", "Quick recap: [3 KEY POINTS]. Save this and follow for more."),
        ],
        visual=[
            "Headline in the top third, supporting text below, same position on every slide.",
            "A small progress indicator (1/7, 2/7…) in a corner.",
            "Alternate background tone on the example slide to make it stand out.",
        ],
        cta="Save this and follow for more practical lessons.",
    ),
    dict(
        name="Before / After",
        purpose="Show a transformation and what caused it. Works for results, skills, spaces, designs and processes.",
        format="Carousel · 5 slides · 1080 × 1350 px",
        slides=[("Hook", "The change in one line"), ("Before", "Specific starting point"), ("After", "Specific result"), ("What changed", "2–3 key actions"), ("CTA", "Realistic next step")],
        copy=[
            ("Slide 1", "Before vs after: [THING] in [TIME PERIOD]"),
            ("Slide 2", "Before: [SPECIFIC STARTING SITUATION]"),
            ("Slide 3", "After: [SPECIFIC RESULT]"),
            ("Slide 4", "What made the difference: [ACTION 1], [ACTION 2], [ACTION 3]"),
            ("Slide 5", "Results vary — but the process works. Want the steps? Save this."),
        ],
        visual=[
            "Use real photos or screenshots for before and after, same angle and crop.",
            "Label “Before” and “After” clearly in small caps.",
            "Don’t edit the “before” to look worse than it was — audiences notice.",
        ],
        cta="Want the full process? Comment “steps” and I’ll share it.",
    ),
    dict(
        name="FAQ",
        purpose="Answer the questions your audience keeps asking. Reduces doubts and positions you as the go-to person.",
        format="Carousel · 6 slides · 1080 × 1350 px",
        slides=[("Cover", "Your questions, answered"), ("Q1", "Question + answer"), ("Q2", "Question + answer"), ("Q3", "Question + answer"), ("Q4", "Question + answer"), ("CTA", "Ask more")],
        copy=[
            ("Slide 1", "[TOPIC]: your most asked questions, answered"),
            ("Slides 2–5", "Q: [REAL QUESTION FROM YOUR AUDIENCE] / A: [CLEAR ANSWER IN 2–3 SENTENCES]"),
            ("Slide 6", "Got a question I didn’t answer? Ask in the comments."),
        ],
        visual=[
            "Question in bold at the top, answer in regular weight below.",
            "A large “Q” in your accent color as a recurring design element.",
            "Keep answers short; link to a longer guide if needed.",
        ],
        cta="Got another question? Ask below and I’ll answer it.",
    ),
    dict(
        name="Myth vs Fact",
        purpose="Correct misconceptions in your niche. Positions you as a trustworthy, evidence-minded voice.",
        format="Carousel · 6 slides · 1080 × 1350 px",
        slides=[("Cover", "Myths you still believe?"), ("Myth 1", "Myth / fact"), ("Myth 2", "Myth / fact"), ("Myth 3", "Myth / fact"), ("Myth 4", "Myth / fact"), ("CTA", "Discuss + share")],
        copy=[
            ("Slide 1", "4 [TOPIC] myths it’s time to stop believing"),
            ("Slides 2–5", "MYTH: [COMMON BELIEF] / FACT: [WHAT’S CLOSER TO THE TRUTH] / Takeaway: [ACTION]"),
            ("Slide 6", "Which myth did you believe? Share this with someone who still does."),
        ],
        visual=[
            "Top half: “MYTH” label, muted color. Bottom half: “FACT” label, accent color.",
            "Avoid red/green only — use labels so it’s accessible.",
            "If a fact needs a source, add it in small text at the bottom of the slide.",
        ],
        cta="Which myth surprised you most?",
        note="Fact-check every “fact” before posting. Accuracy is your reputation.",
    ),
    dict(
        name="Step-by-Step",
        purpose="Walk your audience through a process from start to finish. Ideal for tutorials and how-to content.",
        format="Carousel · 7 slides · 1080 × 1350 px",
        slides=[("Cover", "How to [RESULT]"), ("Step 1", "Verb-first action"), ("Step 2", "Verb-first action"), ("Step 3", "Verb-first action"), ("Step 4", "Verb-first action"), ("Step 5", "Verb-first action"), ("CTA", "Save + try")],
        copy=[
            ("Slide 1", "How to [RESULT] in 5 steps (even if you’re new)"),
            ("Slides 2–6", "Step [NUMBER]: [ACTION] — [ONE TIP OR DETAIL]"),
            ("Slide 7", "Save this and try step 1 today."),
        ],
        visual=[
            "Large step numbers and a thin progress line connecting slides.",
            "Add a screenshot or photo for steps that are hard to picture.",
            "Same font sizes and positions on every step slide.",
        ],
        cta="Save this and try step 1 today.",
    ),
    dict(
        name="Announcement",
        purpose="Share news clearly: a launch, an event, a new offer, a change or a milestone.",
        format="Single image + 3 Story frames · 1080 × 1350 px / 1080 × 1920 px",
        slides=[("Post", "Headline + key detail"), ("Story 1", "Teaser"), ("Story 2", "Details"), ("Story 3", "Link / action")],
        copy=[
            ("Post", "It’s here: [EVENT] — [ONE-LINE BENEFIT]"),
            ("Story 1", "Something new is coming… (countdown sticker)"),
            ("Story 2", "What · who it’s for · when · where"),
            ("Story 3", "Tap the link sticker to [ACTION]"),
        ],
        visual=[
            "One bold headline, one supporting line, plenty of space.",
            "Use your brand’s strongest color on announcement posts only, so they stand out.",
            "Include the date in large type if the event is time-specific.",
        ],
        cta="Tap the link in bio to find out more.",
    ),
    dict(
        name="Product Promotion",
        purpose="Present your offer clearly and calmly: the problem, the solution, what’s inside and how to get it.",
        format="Carousel · 6 slides · 1080 × 1350 px",
        slides=[("Problem", "Recognizable pain"), ("Solution", "Introduce offer"), ("Inside", "What they get"), ("For", "Who it’s for"), ("How", "How to get it"), ("CTA", "Link + reassurance")],
        copy=[
            ("Slide 1", "Tired of [PROBLEM]?"),
            ("Slide 2", "Meet [PRODUCT] — [ONE-LINE DESCRIPTION]"),
            ("Slide 3", "What’s inside: [3–5 COMPONENTS WITH BENEFITS]"),
            ("Slide 4", "Perfect for [TARGET AUDIENCE] who want [RESULT]"),
            ("Slide 5", "How it works: buy → download → start today"),
            ("Slide 6", "Get it through the link in bio. Questions? Send me a message."),
        ],
        visual=[
            "Show the actual product (mockup, screenshots or photos) on slides 2–3.",
            "Price only on the final slides, never on the cover.",
            "Use the same visual style as your educational posts, so promotion feels native.",
        ],
        cta="Get it through the link in bio.",
    ),
    dict(
        name="Testimonial",
        purpose="Let a customer’s words build trust for you. Social proof works best when it’s specific.",
        format="Single image or 3-slide carousel · 1080 × 1350 px",
        slides=[("Quote", "Strongest line"), ("Context", "Before + what they did"), ("CTA", "Invitation")],
        copy=[
            ("Slide 1", "“[CUSTOMER’S EXACT WORDS — THE MOST SPECIFIC LINE]” — [FIRST NAME OR INITIALS]"),
            ("Slide 2", "[NAME] came to me with [SITUATION]. Together we [ACTION]. Here’s what changed: [RESULT]."),
            ("Slide 3", "Want a similar result? Here’s how to start: [NEXT STEP]."),
        ],
        visual=[
            "Large quotation marks as a design element, in your accent color.",
            "A screenshot of the original message (with personal details hidden) adds authenticity.",
            "Customer photo only with explicit permission.",
        ],
        cta="Want results like this? Message me to see if it’s a fit.",
        note="Always get permission, and never edit a customer’s words to change their meaning.",
    ),
    dict(
        name="Behind the Scenes",
        purpose="Show the work behind your work. Builds trust and makes your brand feel human.",
        format="Carousel or Reel · 5 frames · 1080 × 1350 px / 1080 × 1920 px",
        slides=[("Hook", "What you’re showing"), ("Start", "The beginning"), ("Process", "The messy middle"), ("Result", "The finished thing"), ("CTA", "Invite questions")],
        copy=[
            ("Frame 1", "What goes into [THING] (that nobody sees)"),
            ("Frame 2", "It starts with [FIRST STEP]…"),
            ("Frame 3", "Then the part that takes the longest: [PROCESS]"),
            ("Frame 4", "And finally: [RESULT]"),
            ("Frame 5", "Questions about the process? Ask away."),
        ],
        visual=[
            "Real, unpolished photos or clips — authenticity matters more than polish here.",
            "Short text overlays, one per frame.",
            "Use natural light and show your hands, tools and workspace.",
        ],
        cta="Want to see more of the process? Follow along.",
    ),
    dict(
        name="Storytelling",
        purpose="Tell a short personal story with a lesson your audience can use.",
        format="Carousel · 7 slides · 1080 × 1350 px",
        slides=[("Hook", "Start in the moment"), ("Setting", "Where/when"), ("Problem", "The tension"), ("Turn", "What changed"), ("Lesson", "The insight"), ("Apply", "What you can do"), ("CTA", "Question")],
        copy=[
            ("Slide 1", "[A SPECIFIC MOMENT, IN ONE LINE]"),
            ("Slide 2", "It was [TIME], and I was [SITUATION]."),
            ("Slide 3", "The problem: [WHAT WENT WRONG OR WHAT I WAS STRUGGLING WITH]"),
            ("Slide 4", "Then [THE TURNING POINT]."),
            ("Slide 5", "What I learned: [LESSON IN ONE SENTENCE]"),
            ("Slide 6", "If you’re in a similar place: [ONE PRACTICAL ACTION]"),
            ("Slide 7", "Has this happened to you? Tell me below."),
        ],
        visual=[
            "Text-led slides with a personal photo on slide 1 or 2.",
            "Larger text, fewer words — one moment per slide.",
            "Warm, consistent colors; avoid busy backgrounds.",
        ],
        cta="Has something similar happened to you?",
    ),
    dict(
        name="Problem → Solution",
        purpose="Name a specific problem and deliver a clear solution. Direct, useful and easy to create.",
        format="Carousel · 5 slides · 1080 × 1350 px",
        slides=[("Problem", "Name it"), ("Why", "The cause"), ("Solution", "The fix"), ("How", "Steps"), ("CTA", "Save")],
        copy=[
            ("Slide 1", "Struggling with [PROBLEM]?"),
            ("Slide 2", "It’s usually because [CAUSE] — not because you’re doing something wrong."),
            ("Slide 3", "The fix: [SOLUTION IN ONE SENTENCE]"),
            ("Slide 4", "How to do it: 1. [STEP] 2. [STEP] 3. [STEP]"),
            ("Slide 5", "Save this for the next time [PROBLEM] shows up."),
        ],
        visual=[
            "Problem slide in a muted or dark tone; solution slides in your bright accent.",
            "This visual shift signals the turn from problem to answer.",
            "Keep the steps slide to three steps maximum.",
        ],
        cta="Save this for the next time it happens.",
    ),
]
